name: Deploy Static Website to Plesk
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          rm -rf out
          mkdir out
          rsync -a ./ out/ --exclude '.git' --exclude '.github' --exclude 'out'

      - name: Publish to deploy branch
        run: |
          cd out
          git init
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy $(date -u +'%Y-%m-%d %H:%M:%S')"
          git branch -M deploy
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} deploy
